//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.11 at 05:23:47 PM WET 
//


package pt.lsts.imc.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.lsts.imc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Field_QNAME = new QName("", "field");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.lsts.imc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link Messages.Groups }
     * 
     */
    public Messages.Groups createMessagesGroups() {
        return new Messages.Groups();
    }

    /**
     * Create an instance of {@link Messages.MessageGroups }
     * 
     */
    public Messages.MessageGroups createMessagesMessageGroups() {
        return new Messages.MessageGroups();
    }

    /**
     * Create an instance of {@link Messages.Bitfields }
     * 
     */
    public Messages.Bitfields createMessagesBitfields() {
        return new Messages.Bitfields();
    }

    /**
     * Create an instance of {@link Messages.Enumerations }
     * 
     */
    public Messages.Enumerations createMessagesEnumerations() {
        return new Messages.Enumerations();
    }

    /**
     * Create an instance of {@link UnitsType }
     * 
     */
    public UnitsType createUnitsType() {
        return new UnitsType();
    }

    /**
     * Create an instance of {@link SerializationType }
     * 
     */
    public SerializationType createSerializationType() {
        return new SerializationType();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link DocumentationType }
     * 
     */
    public DocumentationType createDocumentationType() {
        return new DocumentationType();
    }

    /**
     * Create an instance of {@link TypesType }
     * 
     */
    public TypesType createTypesType() {
        return new TypesType();
    }

    /**
     * Create an instance of {@link FlagsType }
     * 
     */
    public FlagsType createFlagsType() {
        return new FlagsType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link EnumBitmaskType }
     * 
     */
    public EnumBitmaskType createEnumBitmaskType() {
        return new EnumBitmaskType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link FlagType }
     * 
     */
    public FlagType createFlagType() {
        return new FlagType();
    }

    /**
     * Create an instance of {@link SubtypeType }
     * 
     */
    public SubtypeType createSubtypeType() {
        return new SubtypeType();
    }

    /**
     * Create an instance of {@link Messages.Groups.Group }
     * 
     */
    public Messages.Groups.Group createMessagesGroupsGroup() {
        return new Messages.Groups.Group();
    }

    /**
     * Create an instance of {@link Messages.MessageGroups.MessageGroup }
     * 
     */
    public Messages.MessageGroups.MessageGroup createMessagesMessageGroupsMessageGroup() {
        return new Messages.MessageGroups.MessageGroup();
    }

    /**
     * Create an instance of {@link Messages.Bitfields.Def }
     * 
     */
    public Messages.Bitfields.Def createMessagesBitfieldsDef() {
        return new Messages.Bitfields.Def();
    }

    /**
     * Create an instance of {@link Messages.Enumerations.Def }
     * 
     */
    public Messages.Enumerations.Def createMessagesEnumerationsDef() {
        return new Messages.Enumerations.Def();
    }

    /**
     * Create an instance of {@link UnitsType.Unit }
     * 
     */
    public UnitsType.Unit createUnitsTypeUnit() {
        return new UnitsType.Unit();
    }

    /**
     * Create an instance of {@link SerializationType.Type }
     * 
     */
    public SerializationType.Type createSerializationTypeType() {
        return new SerializationType.Type();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field")
    public JAXBElement<FieldType> createField(FieldType value) {
        return new JAXBElement<FieldType>(_Field_QNAME, FieldType.class, null, value);
    }

}
